import { CheckSquare, FileUp, PackageSearch, RefreshCcw, Search, Square, Zap } from "lucide-react";
import type { MarketingEntity } from "../../domain/doudian/marketing";

export function MarketingProductTable({ rows, totalRows = rows.length, search, loading, selectedIds = new Set<string>(), importValue = "", onToggle, onToggleAll, onSearch, onRefresh, onQuickLoad, onImportValueChange, onImport }: { rows: MarketingEntity[]; totalRows?: number; search: string; loading: boolean; selectedIds?: ReadonlySet<string>; importValue?: string; onToggle?: (row: MarketingEntity) => void; onToggleAll?: (rows: MarketingEntity[]) => void; onSearch: (value: string) => void; onRefresh: () => void; onQuickLoad?: () => void; onImportValueChange?: (value: string) => void; onImport?: () => void }) {
  const allSelected = rows.length > 0 && rows.every((row) => selectedIds.has(`${row.shopId}:${row.entityId}`));
  return (
    <div className="min-h-0 flex-1 overflow-auto border-t border-[#e6ebf3]">
      <div className="sticky top-0 z-10 flex min-h-10 items-center justify-between gap-3 border-b border-[#e6ebf3] bg-[#f8fafc] px-4 max-[600px]:flex-wrap max-[600px]:py-2">
        <span className="text-[12px] font-semibold text-[#344054]">可参与商品 · {rows.length}{totalRows !== rows.length ? ` / ${totalRows}` : ""}</span>
        <div className="flex min-w-0 flex-wrap items-center justify-end gap-2"><label className="relative w-[200px] max-w-full"><Search className="pointer-events-none absolute left-2 top-1/2 size-3.5 -translate-y-1/2 text-[#98a2b3]" /><input className="h-7 w-full rounded-md border border-[#dbe3ee] bg-white pl-7 pr-2 text-[11px] outline-none focus:border-[#ff5020]" aria-label="筛选商品" placeholder="商品名称 / 商品 ID" value={search} onChange={(event) => onSearch(event.target.value)} /></label>{onImportValueChange && onImport ? <><input className="h-7 w-[190px] rounded-md border border-[#dbe3ee] bg-white px-2 text-[11px] outline-none focus:border-[#ff5020]" aria-label="导入商品 ID" placeholder="商品 ID，逗号或换行分隔" value={importValue} onChange={(event) => onImportValueChange(event.target.value)} /><button className="inline-flex h-7 items-center gap-1 rounded-md border border-[#dbe3ee] bg-white px-2 text-[11px] font-semibold text-[#344054] disabled:opacity-50" type="button" title="按商品 ID 加载" disabled={loading || !importValue.trim()} onClick={onImport}><FileUp className="size-3.5" />导入</button></> : null}{onQuickLoad ? <button className="inline-flex h-7 items-center gap-1 rounded-md border border-[#dbe3ee] bg-white px-2 text-[11px] font-semibold text-[#344054] disabled:opacity-50" type="button" title="快速加载前 1000 个可参与商品" disabled={loading} onClick={onQuickLoad}><Zap className="size-3.5" />快速加载</button> : null}<button className="inline-flex h-7 items-center gap-1 rounded-md border border-[#dbe3ee] bg-white px-2 text-[11px] font-semibold text-[#344054] disabled:opacity-50" type="button" title="全量加载商品资格" disabled={loading} onClick={onRefresh}><RefreshCcw className={`size-3.5 ${loading ? "animate-spin" : ""}`} />全量加载</button></div>
      </div>
      {rows.length ? (
        <table className="w-full min-w-[720px] border-collapse text-left text-[12px]">
          <thead><tr className="border-b border-[#edf1f6] text-[#667085]"><th className="w-10 px-4 py-2.5"><button className="grid size-6 place-items-center text-[#52627a]" type="button" title={allSelected ? "取消选择当前商品" : "选择当前商品"} aria-label={allSelected ? "取消选择当前商品" : "选择当前商品"} onClick={() => onToggleAll?.(rows)}>{allSelected ? <CheckSquare className="size-4 text-[#ff5020]" /> : <Square className="size-4" />}</button></th><th className="px-2 py-2.5 font-semibold">商品</th><th className="px-3 py-2.5 font-semibold">商品 ID</th><th className="px-3 py-2.5 font-semibold">店铺</th><th className="px-3 py-2.5 font-semibold">SKU / 价格 / 库存</th><th className="px-3 py-2.5 font-semibold">资格结果</th></tr></thead>
          <tbody>{rows.map((row, index) => { const selected = selectedIds.has(`${row.shopId}:${row.entityId}`); return <tr className={`border-b border-[#edf1f6] text-[#344054] ${selected ? "bg-[#fffaf6]" : ""}`} key={`${row.shopId}-${row.entityId}-${index}`}><td className="px-4 py-3"><button className="grid size-6 place-items-center text-[#52627a]" type="button" title={selected ? "取消选择商品" : "选择商品"} aria-label={selected ? "取消选择商品" : "选择商品"} onClick={() => onToggle?.(row)}>{selected ? <CheckSquare className="size-4 text-[#ff5020]" /> : <Square className="size-4" />}</button></td><td className="max-w-[320px] px-2 py-3 font-medium text-[#1d2939]"><span className="block truncate" title={row.name}>{row.name}</span></td><td className="px-3 py-3 font-mono text-[11px]">{row.entityId || "-"}</td><td className="px-3 py-3">{row.shopName}</td><td className="px-3 py-3 text-[11px] text-[#52627a]">{row.skuCount || row.productCount || 1} SKU · {row.priceFen != null ? `${(row.priceFen / 100).toFixed(2)} 元` : "价格待校验"} · {row.inventory != null ? `${row.inventory} 库存` : "库存待校验"}</td><td className="max-w-[260px] px-3 py-3"><span className={row.platformError || row.eligible === false ? "text-[#b42318]" : "text-[#087443]"}>{row.platformError || row.failureReason || "可参与"}</span></td></tr>; })}</tbody>
        </table>
      ) : <div className="grid min-h-[220px] place-items-center px-4 text-center"><div><PackageSearch className="mx-auto size-8 text-[#b8c2d0]" /><p className="mb-0 mt-3 text-[12px] text-[#667085]">选择店铺和活动参数后刷新商品资格</p></div></div>}
    </div>
  );
}
