export const REMOTE_BROWSER_COMMAND = Object.freeze({
  goto: 'goto',
  back: 'back',
  forward: 'forward',
  reload: 'reload',
  stop: 'stop',
  navigationStop: 'navigation.stop',
  getCurrentUrl: 'getCurrentUrl',
  title: 'title',
  waitForSelector: 'waitForSelector',
  click: 'click',
  type: 'type',
  select: 'select',
  getText: 'getText',
  getAttribute: 'getAttribute',
  evaluate: 'evaluate',
  evaluateWithArgs: 'evaluateWithArgs',
  screenshot: 'screenshot',
  pdfSave: 'pdf.save',
  cookiesGetAll: 'cookies.getAll',
  cookiesSet: 'cookies.set',
  cookiesClear: 'cookies.clear',
  storageGetItem: 'storage.getItem',
  storageSetItem: 'storage.setItem',
  storageRemoveItem: 'storage.removeItem',
  storageClearArea: 'storage.clearArea',
  networkStart: 'network.start',
  networkStop: 'network.stop',
  networkClear: 'network.clear',
  consoleStart: 'console.start',
  consoleStop: 'console.stop',
  consoleClear: 'console.clear',
  show: 'show',
  hide: 'hide',
  clientStateGet: 'clientState.get',
  dialogArm: 'dialog.arm',
  dialogDisarm: 'dialog.disarm',
  dialogWait: 'dialog.wait',
  dialogHandle: 'dialog.handle',
  tabsList: 'tabs.list',
  tabsCreate: 'tabs.create',
  tabsActivate: 'tabs.activate',
  tabsClose: 'tabs.close',
  emulationIdentitySet: 'emulation.identity.set',
  emulationViewportSet: 'emulation.viewport.set',
  emulationClear: 'emulation.clear',
  nativeClick: 'native.click',
  nativeMove: 'native.move',
  nativeDrag: 'native.drag',
  nativeType: 'native.type',
  nativeKeyPress: 'native.keyPress',
  nativeScroll: 'native.scroll',
  touchTap: 'touch.tap',
  touchLongPress: 'touch.longPress',
  touchDrag: 'touch.drag',
  windowOpenSetPolicy: 'windowOpen.setPolicy',
  windowOpenClearPolicy: 'windowOpen.clearPolicy',
  downloadSetBehavior: 'download.setBehavior',
  downloadList: 'download.list',
  downloadWait: 'download.wait',
  downloadCancel: 'download.cancel',
  networkInterceptEnable: 'network.intercept.enable',
  networkInterceptDisable: 'network.intercept.disable',
  networkInterceptContinue: 'network.intercept.continue',
  networkInterceptFulfill: 'network.intercept.fulfill',
  networkInterceptFail: 'network.intercept.fail',
} as const);

export const COMMON_REMOTE_BROWSER_COMMANDS = [
  REMOTE_BROWSER_COMMAND.goto,
  REMOTE_BROWSER_COMMAND.back,
  REMOTE_BROWSER_COMMAND.forward,
  REMOTE_BROWSER_COMMAND.reload,
  REMOTE_BROWSER_COMMAND.getCurrentUrl,
  REMOTE_BROWSER_COMMAND.title,
  REMOTE_BROWSER_COMMAND.evaluate,
  REMOTE_BROWSER_COMMAND.evaluateWithArgs,
  REMOTE_BROWSER_COMMAND.screenshot,
  REMOTE_BROWSER_COMMAND.cookiesGetAll,
  REMOTE_BROWSER_COMMAND.cookiesSet,
  REMOTE_BROWSER_COMMAND.cookiesClear,
  REMOTE_BROWSER_COMMAND.show,
  REMOTE_BROWSER_COMMAND.hide,
  REMOTE_BROWSER_COMMAND.dialogWait,
  REMOTE_BROWSER_COMMAND.dialogHandle,
  REMOTE_BROWSER_COMMAND.tabsList,
  REMOTE_BROWSER_COMMAND.tabsCreate,
  REMOTE_BROWSER_COMMAND.tabsActivate,
  REMOTE_BROWSER_COMMAND.tabsClose,
  REMOTE_BROWSER_COMMAND.nativeClick,
  REMOTE_BROWSER_COMMAND.nativeMove,
  REMOTE_BROWSER_COMMAND.nativeDrag,
  REMOTE_BROWSER_COMMAND.nativeType,
  REMOTE_BROWSER_COMMAND.nativeKeyPress,
  REMOTE_BROWSER_COMMAND.nativeScroll,
  REMOTE_BROWSER_COMMAND.windowOpenSetPolicy,
  REMOTE_BROWSER_COMMAND.windowOpenClearPolicy,
] as const;

export const EXTENSION_REMOTE_BROWSER_COMMANDS = [
  ...COMMON_REMOTE_BROWSER_COMMANDS,
  REMOTE_BROWSER_COMMAND.emulationIdentitySet,
  REMOTE_BROWSER_COMMAND.emulationViewportSet,
  REMOTE_BROWSER_COMMAND.emulationClear,
  REMOTE_BROWSER_COMMAND.navigationStop,
  REMOTE_BROWSER_COMMAND.waitForSelector,
  REMOTE_BROWSER_COMMAND.click,
  REMOTE_BROWSER_COMMAND.type,
  REMOTE_BROWSER_COMMAND.select,
  REMOTE_BROWSER_COMMAND.getText,
  REMOTE_BROWSER_COMMAND.getAttribute,
  REMOTE_BROWSER_COMMAND.networkStart,
  REMOTE_BROWSER_COMMAND.networkStop,
  REMOTE_BROWSER_COMMAND.networkClear,
  REMOTE_BROWSER_COMMAND.consoleStart,
  REMOTE_BROWSER_COMMAND.consoleStop,
  REMOTE_BROWSER_COMMAND.consoleClear,
  REMOTE_BROWSER_COMMAND.clientStateGet,
  REMOTE_BROWSER_COMMAND.dialogArm,
  REMOTE_BROWSER_COMMAND.dialogDisarm,
  REMOTE_BROWSER_COMMAND.networkInterceptEnable,
  REMOTE_BROWSER_COMMAND.networkInterceptDisable,
  REMOTE_BROWSER_COMMAND.networkInterceptContinue,
  REMOTE_BROWSER_COMMAND.networkInterceptFulfill,
  REMOTE_BROWSER_COMMAND.networkInterceptFail,
] as const;

export const RUYI_REMOTE_BROWSER_COMMANDS = [
  ...COMMON_REMOTE_BROWSER_COMMANDS,
  REMOTE_BROWSER_COMMAND.emulationIdentitySet,
  REMOTE_BROWSER_COMMAND.emulationViewportSet,
  REMOTE_BROWSER_COMMAND.emulationClear,
  REMOTE_BROWSER_COMMAND.stop,
  REMOTE_BROWSER_COMMAND.networkInterceptEnable,
  REMOTE_BROWSER_COMMAND.networkInterceptDisable,
  REMOTE_BROWSER_COMMAND.networkInterceptContinue,
  REMOTE_BROWSER_COMMAND.networkInterceptFulfill,
  REMOTE_BROWSER_COMMAND.networkInterceptFail,
  REMOTE_BROWSER_COMMAND.touchTap,
  REMOTE_BROWSER_COMMAND.touchLongPress,
  REMOTE_BROWSER_COMMAND.touchDrag,
  REMOTE_BROWSER_COMMAND.downloadSetBehavior,
  REMOTE_BROWSER_COMMAND.downloadList,
  REMOTE_BROWSER_COMMAND.downloadWait,
  REMOTE_BROWSER_COMMAND.downloadCancel,
  REMOTE_BROWSER_COMMAND.pdfSave,
  REMOTE_BROWSER_COMMAND.storageGetItem,
  REMOTE_BROWSER_COMMAND.storageSetItem,
  REMOTE_BROWSER_COMMAND.storageRemoveItem,
  REMOTE_BROWSER_COMMAND.storageClearArea,
] as const;

export type CommonRemoteBrowserCommand = (typeof COMMON_REMOTE_BROWSER_COMMANDS)[number];
export type ExtensionRemoteBrowserCommand = (typeof EXTENSION_REMOTE_BROWSER_COMMANDS)[number];
export type RuyiRemoteBrowserCommand = (typeof RUYI_REMOTE_BROWSER_COMMANDS)[number];
export type RemoteBrowserCommand = ExtensionRemoteBrowserCommand | RuyiRemoteBrowserCommand;
